version: '3.8'
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
    volumes:
      - .:/app 
    depends_on:
      - mysql-db
    networks:
      - my-network

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: file_data
      MYSQL_USER: root1
      MYSQL_PASSWORD: nopasswordatall
    ports:
      - "3306:3306"
    networks:
      - my-network

  nextcloud:
    image: nextcloud
    ports:
      - "8080:80"
    networks:
      - my-network
      
networks:
  my-network:
